"""empty message

Revision ID: 370c4dd7ad37
Revises: c2d22a9fedca
Create Date: 2024-06-05 21:20:04.221151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370c4dd7ad37'
down_revision: Union[str, None] = 'c2d22a9fedca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'trip', ['trip_id'], ['id'])
    op.drop_constraint('trip_order_id_fkey', 'trip', type_='foreignkey')
    op.drop_column('trip', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trip_order_id_fkey', 'trip', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'trip_id')
    # ### end Alembic commands ###
