"""add Date to trip

Revision ID: 49d0b9fa5e05
Revises: 370c4dd7ad37
Create Date: 2024-06-06 02:00:47.394539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d0b9fa5e05'
down_revision: Union[str, None] = '370c4dd7ad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('departure_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'departure_date')
    # ### end Alembic commands ###
