"""Create User model

Revision ID: a01f08132674
Revises: 
Create Date: 2024-06-01 20:46:36.104630

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01f08132674'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
