"""Change email field to default string

Revision ID: c2d22a9fedca
Revises: 6c978a3b31ed
Create Date: 2024-06-05 10:05:06.940421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d22a9fedca'
down_revision: Union[str, None] = '6c978a3b31ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_trip_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'trip_id')
    op.add_column('trip', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'order', ['order_id'], ['id'])
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'order_id')
    op.add_column('order', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_trip_id_fkey', 'order', 'trip', ['trip_id'], ['id'])
    # ### end Alembic commands ###
